// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzvzgzrnttwifklzbdci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6dnpnenJudHR3aWZrbHpiZGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjk1MjQsImV4cCI6MjA2MDkwNTUyNH0.Jjd6UNL-8Ov3JlZOQud4SCNr9-rrGgJtExM39Wejr4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);